/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_study_com_jnibsetpractice_Jni */

#ifndef _Included_jni_study_com_jnibsetpractice_Jni
#define _Included_jni_study_com_jnibsetpractice_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_study_com_jnibsetpractice_Jni
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_study_com_jnibsetpractice_Jni_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     jni_study_com_jnibsetpractice_Jni
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jni_study_com_jnibsetpractice_Jni_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jni_study_com_jnibsetpractice_Jni
 * Method:    transe_string
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_study_com_jnibsetpractice_Jni_transe_1string
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jni_study_com_jnibsetpractice_Jni
 * Method:    transeIntArray
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_jni_study_com_jnibsetpractice_Jni_transeIntArray
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     jni_study_com_jnibsetpractice_Jni
 * Method:    callBackMethodVoid
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_study_com_jnibsetpractice_Jni_callBackMethodVoid
  (JNIEnv *, jobject);

/*
 * Class:     jni_study_com_jnibsetpractice_Jni
 * Method:    callBackMethodInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jni_study_com_jnibsetpractice_Jni_callBackMethodInt
  (JNIEnv *, jobject);

/*
 * Class:     jni_study_com_jnibsetpractice_Jni
 * Method:    callbackMethodString
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_study_com_jnibsetpractice_Jni_callbackMethodString
  (JNIEnv *, jobject);

/*
 * Class:     jni_study_com_jnibsetpractice_Jni
 * Method:    callbackMethodToast
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_study_com_jnibsetpractice_Jni_callbackMethodToast
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
